### PR TITLE
Add non-interactive pendulum environment.

### PR DESCRIPTION
**Pull request by aterenin**
Often times, it's useful to have environments that have no actions for debugging purposes. This adds a simple pendulum as such an environment.

### CODE REVIEW

**Comment by aterenin** [comment]
This will fail CI because it relies on upstream changes in RLBase here: https://github.com/JuliaReinforcementLearning/ReinforcementLearningBase.jl/pull/26/files

**Comment by findmyway** [comment]
I guess that for all the `NonInteractiveEnv`s, the only acceptable action is `nothing`?

If that is the case, can we also add another method like `env() = env(nothing)`?

**Comment by aterenin** [comment]
Yeah, this is the idea. Basically you set a policy that always returns `nothing`. I'll add this syntax.

I got the tests to run, and it turns out this PR fails because due to a type error I just fixed upstream. Let me get this into a passing state.

**Comment by aterenin** [comment]
Okay, looks like this fails CI due to upstream changes not yet being visible on Travis. On my end, I'm seeing the following (other tests are commented).
```
(ReinforcementLearningEnvironments) pkg> test
   Testing ReinforcementLearningEnvironments
 Resolving package versions...
[ Info: Testing MountainCarEnv()
[ Info: Testing ContinuousMountainCarEnv()
[ Info: Testing PendulumEnv()
[ Info: Testing PendulumNonInteractiveEnv()
Test Summary:                     | Pass  Total
ReinforcementLearningEnvironments | 1212   1212
   Testing ReinforcementLearningEnvironments tests passed 

```

**Comment by findmyway** [comment]
Thanks. Merged

**Pull request merged**
